services:

  redis:
    image: redis:latest

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: zeus
      POSTGRES_PASSWORD: zeus
      POSTGRES_DB: zeus
    ports:
      - "5432:5432"
    volumes:
      - ./db_data:/var/lib/postgresql:rw

  dev:
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"

    build:
      context: .
      target: zeus_dev
    volumes:
      - .:/home/user/zeus:rw
    working_dir: /home/user/zeus
    environment:
      - PGHOST
      - PGDATABASE
      - PGUSER
      - PGPASSWORD
    depends_on:
      - redis
      - db

  dev_celery:
    command: celery -A zeus.celery worker -l INFO --concurrency 1 --pool solo

    build:
      context: .
      target: zeus_dev
    volumes:
      - .:/home/user/zeus:rw
    working_dir: /home/user/zeus
    environment:
      - PGHOST
      - PGDATABASE
      - PGUSER
      - PGPASSWORD
    depends_on:
      - redis
